const microgreens = [
    {
        name: 'Wheatgrass',
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        image: 'https://photos.app.goo.gl/jzV8PdVPzq6QEK7VA',
    },
    {
        name: "Bull's Blood",
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        image: 'https://photos.app.goo.gl/6MZLDEZLPFFD4B8V7',
    },
    {
        name: "Basil",
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        image: 'https://photos.app.goo.gl/W7gGHHYjM7CcpsTt7',
    },
    {
        name: "Nasturtium",
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        image: 'https://photos.app.goo.gl/qAs4hnsZmp2KZ8AR8',
    },
    {
        name: "African Blue Basil",
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        image: 'https://photos.app.goo.gl/oHaSkrrHYQaDxhMX9',
    },
    {
        name: "Dill",
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        image: 'https://photos.app.goo.gl/oA4KJEjf91dKnDhaA',
    },
    {
        name: "Lemon Thyme",
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        image: 'https://photos.app.goo.gl/oA4KJEjf91dKnDhaA',
    },
    {
        name: "Honeydew Sage",
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        image: 'https://photos.app.goo.gl/ecGfhGnMr2K7HnmG8',
    },
    {
        name: "Hyssop",
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        image: 'https://photos.app.goo.gl/afJo1onDYqkMjNqn7',
    }
]
export default microgreens