//import pics
const traditionalProduce = [
    {
        name: 'Cherry Tomatoes',
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        image: 'https://photos.app.goo.gl/1BLDCQV6bJBQWPeu9',
    },
    {
        name: 'Habnero',
        category: 'traditionalproduce',
        amount: '1 Oz',
        price: '$12.48',
        description: 'Seed from Mayan origin',
        image: 'https://photos.app.goo.gl/R8Q9WymSF8RvEJRW9',
    },
    {
        name: 'Jalapeno',
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        image: 'https://photos.app.goo.gl/NBZwAowYUwCXurw8A',
    },
    {
        name: 'Cool Mushroom',
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        image: 'https://photos.app.goo.gl/X8LWTErogLZRrWA76',
    },
    {
        name: 'Peas',
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        image: 'https://photos.app.goo.gl/tppKWAK1fvtcwMEm8',
    },
    {
        name: 'Raspberry',
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        image: 'https://photos.app.goo.gl/HpsWgirtoHcT3YMc9',
    },
    {
        name: 'Carrots',
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        image: 'https://photos.app.goo.gl/iFJggYhoExo8dm476',
    },
    {
        name: 'Green Strawberry ',
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        image: 'https://photos.app.goo.gl/tD5MEGdtXugaF9XU9',
    },
    {
        name: 'Radish',
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        image: 'https://photos.app.goo.gl/hdTVYZoYfAXegnXw9',
    },
    {
        name: 'Leek',
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        image: 'https://photos.app.goo.gl/ZNoGCg9LCQSHpYh68',
    }
]
export default traditionalProduce