import { Carrot, CherryTomato, CoolMushroom, Jalapeno, Leek, Peas, Raddish, Raspberry, Habnero, GreenStrawberry } from '../images/'
const traditionalProduce = [
    {
        name: 'Cherry Tomatoes',
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        imageurl: 'https://photos.app.goo.gl/1BLDCQV6bJBQWPeu9',
        imageref: CherryTomato,
    },
    {
        name: 'Habnero',
        category: 'traditionalproduce',
        amount: '1 Oz',
        price: '$12.48',
        description: 'Seed from Mayan origin',
        imageurl: 'https://photos.app.goo.gl/R8Q9WymSF8RvEJRW9',
        imageref: Habnero,
    },
    {
        name: 'Jalapeno',
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        imageurl: 'https://photos.app.goo.gl/NBZwAowYUwCXurw8A',
        imageref: Jalapeno,
    },
    {
        name: 'Cool Mushroom',
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        imageurl: 'https://photos.app.goo.gl/X8LWTErogLZRrWA76',
        imageref: CoolMushroom,
    },
    {
        name: 'Peas',
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        imageurl: 'https://photos.app.goo.gl/tppKWAK1fvtcwMEm8',
        imageref: Peas,
    },
    {
        name: 'Raspberry',
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        imageurl: 'https://photos.app.goo.gl/HpsWgirtoHcT3YMc9',
        imageref: Raspberry,
    },
    {
        name: 'Carrots',
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        imageurl: 'https://photos.app.goo.gl/iFJggYhoExo8dm476',
        imageref: Carrot,
    },
    {
        name: 'Green Strawberry ',
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        imageurl: 'https://photos.app.goo.gl/tD5MEGdtXugaF9XU9',
        imageref: GreenStrawberry,
    },
    {
        name: 'Radish',
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        imageurl: 'https://photos.app.goo.gl/hdTVYZoYfAXegnXw9',
        imageref: Raddish,
    },
    {
        name: 'Leek',
        category: 'traditionalproduce',
        amount: '1 pound',
        price: '$1/pound',
        description: 'Seed from Mayan origin',
        imageurl: 'https://photos.app.goo.gl/ZNoGCg9LCQSHpYh68',
        imageref: Leek,
    }
]
export default traditionalProduce